name: Push To main and echo print
on:
  push:
    branches:
    - main
#井字號是用來備註
jobs:  #下面開始定義「job 任務」
  Echo-Something: #job名稱（不允許空格)，job 底下需要 runs-on 或 uses（用別人的workflow）
      runs-on: ubuntu-latest #執行的作業系統
      
      steps: #下面開始定義「step 步驟」，每個步驟可以是 -uses開頭（不取名，用別人的Action），或是 -name開頭先定義名稱，接著定義動作 Action
      - uses: actions/checkout@v4 #有要操作儲存庫程式碼的工作流任務，必須要用checkout，建議是都要加
      
      - name: Echo Someting #步驟名稱
        run: echo "hello" #以作業系統環境執行命令，echo是印出指定文字內容
        
  Call-Other-Worflow:     
      uses: JamesHoOHYA/test/.github/workflows/Call_Workflow.yml@main
      with:
        To_Print_Content: "input something"
      #引用外部workflow的格式 
      #{儲存庫擁有者}/{儲存庫名稱}/{檔案路徑}@{ref引用版本來源，可以是分支或標籤}

