name: Build a git action file

on:
  push:
    branches:
    - main

jobs:
  CHECK:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/setup-node@v4
    
  TestEcho:
    runs-on: ubuntu-latest
    steps:
      - name: Show Output
        run: echo 'here'
  

  
